export const data = [
  {
    id: 1,
    title: 'Who is the primary contact for this policy?',
    description:
      'This person will receive all communications from Newfront about this policy. You can change this contact ' +
      "information later. If you're not sure, just add your contact information",
    order: 1,
    questions: [
      {
        id: 1,
        label: 'Full Name',
        hint: '',
        type: 'text',
        required: false,
        resourceId: 1,
        resourceName: 'Company',
        defaultValue: '',
        value: '',
        placeholder: '',
        visibleByDefault: true,
        order: 1,
        options: null,
        isCustomField: true,
        isSharedField: false,
        validationType: 'string',
        validations: [
          {
            type: 'required',
            params: ['Full Name is required'],
          },
        ],
      },
      {
        id: 2,
        label: 'Role',
        hint: '',
        type: 'text',
        required: false,
        resourceId: 1,
        resourceName: 'Company',
        defaultValue: '',
        value: '',
        placeholder: '',
        visibleByDefault: true,
        order: 1,
        options: null,
        isCustomField: true,
        isSharedField: false,
      },
      {
        id: 1,
        label: 'Phone Number',
        hint: '',
        type: 'text',
        required: false,
        resourceId: 1,
        resourceName: 'Company',
        defaultValue: '',
        value: '',
        placeholder: '',
        visibleByDefault: true,
        order: 1,
        options: null,
        isCustomField: true,
        isSharedField: false,
        validationType: 'string',
        validations: [
          {
            type: 'required',
            params: ['Phone Number is required'],
          },
        ],
      },
      /*{
        id: 2,
        label: 'Description',
        hint: '',
        type: 'textarea',
        required: false,
        resourceId: 1,
        resourceName: 'Company',
        defaultValue: '',
        value: '',
        placeholder: '',
        visibleByDefault: true,
        order: 2,
        options: null,
      },
      {
        id: 3,
        label: 'Options',
        hint: '',
        type: 'radio',
        required: false,
        resourceId: 1,
        resourceName: 'Company',
        defaultValue: '',
        value: '',
        placeholder: '',
        visibleByDefault: true,
        order: 1,
        options: [
          { id: 1, optionId: 0, label: 'A' },
          { id: 2, optionId: 1, label: 'B' },
          { id: 3, optionId: 2, label: 'C' },
        ],
      },*/
    ],
  },
  {
    id: 2,
    title: 'Tell us about your company',
    description: '',
    order: 2,
    questions: [
      {
        id: 1,
        label: 'Company Name',
        hint: '',
        type: 'text',
        required: false,
        resourceId: 1,
        resourceName: 'Company',
        defaultValue: '',
        value: '',
        placeholder: '',
        visibleByDefault: true,
        order: 1,
        options: null,
        isCustomField: true,
        isSharedField: false,
      },
      {
        id: 2,
        label: 'What is your Federal Employer IdentificationNumber? (FEIN)',
        hint: '',
        type: 'number',
        required: false,
        resourceId: 1,
        resourceName: 'Company',
        defaultValue: '',
        value: '',
        placeholder: '',
        visibleByDefault: true,
        order: 2,
        options: null,
      },
      {
        id: 3,
        label: 'Years in business',
        hint: '',
        type: 'number',
        required: false,
        resourceId: 1,
        resourceName: 'Company',
        defaultValue: '',
        value: '',
        placeholder: '',
        visibleByDefault: true,
        order: 3,
        options: null,
      },
      {
        id: 4,
        label: 'Number of locations',
        hint: '',
        type: 'number',
        required: false,
        resourceId: 1,
        resourceName: 'Company',
        defaultValue: '',
        value: '',
        placeholder: '',
        visibleByDefault: true,
        order: 4,
        options: null,
      },
      {
        id: 5,
        label: 'In which states do you operate?',
        hint: '',
        type: 'text',
        required: false,
        resourceId: 1,
        resourceName: 'Company',
        defaultValue: '',
        value: '',
        placeholder: '',
        visibleByDefault: true,
        order: 5,
        options: null,
      },
    ],
  },
];
